<?php
/*************************************************************\
 *  Copyright (C) 2004 Ares China Inc.
 *  Created By Dennis Lan, Lan Jiangtao
 *  Description:
 *    Export Gridview Data to Excel  Dennis 2011-06-15
 *  $HeadURL: https://192.168.0.101/svn/ehr/trunk/eHR/ess/includes/gridview_export_DB.php $
 *  $Id: gridview_export_DB.php 3152 2011-08-01 03:01:19Z dennis $$Rev: 3152 $   
 *  $LastChangedDate: 2008-11-21 09:26:45 +0800 (星期五, 21 十一月 2008) 
 *  $Author: dennis $ 
 ****************************************************************************/

include_once 'PHPExcel.php';
require_once 'PHPExcel/Cell/AdvancedValueBinder.php';
// auto 
ini_set ('error_reporting', E_ALL );
ini_set ('display_errors', 0 );
PHPExcel_Cell::setValueBinder( new PHPExcel_Cell_AdvancedValueBinder());
include_once 'gv_print_exp.php';
//$g_tpl->assign('DOCUMENT_TITLE','导出 Excel');

$lang = $_SESSION['user']['language'];
$appid = $_POST['appid'];
$lastsql = $_POST['lastsql'];

$reportname = getReportName($appid,$lang);

$phpExcel = new PHPExcel(); // init phpexcel instance
// set excel file property
/*
$exceProp = $phpExcel->getProperties();
$exceProp->setCreator('Dennis');
$exceProp->setLastModifiedBy('Dennis');
$exceProp->setTitle($reportname);
$exceProp->setSubject('HR Report');
$exceProp->setDescription('HR Report Generated by ARES eHR System');
$exceProp->setKeywords('PHPExcel, Dennis, ARESCHINA');
$exceProp->setCategory('HR Report');
*/
// set current activate sheet
$phpExcel->setActiveSheetIndex(0);
$currSheet = $phpExcel->getActiveSheet();
$currSheet->setTitle($reportname);

/**
 *  Set Data Column Title
 * @param object $active_sheet
 * @param array $colconfig
 */
function setSheetRowTitle($active_sheet,$colconfig)
{
	$rowIdx = 1;
	$cellIdx = 0;
	foreach ($colconfig as $val)
	{
		$active_sheet->setCellValueByColumnAndRow($cellIdx,$rowIdx,$val['PROMPT_TEXT']);
		$cellIdx++;
	}
}

/**
 * Get Column Data Type
 * @param array $colconfig
 * @param string $colname
 */
function getColDataType($colconfig,$colname)
{
	$data_type = 'VARCHAR2';
	$phpexcel_data_type = '';
	foreach ($colconfig as $val)
	{
		if ($val['TABLE_NAME'].'_'.$val['COLUMN_NAME'] == $colname) 
		{
			$data_type = $val['DATA_TYPE'];
			break;
		}
	}
	switch ($data_type)
	{
		case 'VARCHAR2':
			return PHPExcel_Cell_DataType::TYPE_STRING;
		break;
		case 'NUMBER':
			return PHPExcel_Cell_DataType::TYPE_NUMERIC;
		break;
		case 'DATE':
			return 'date';
		break;
		default:break;	
	}
	return PHPExcel_Cell_DataType::TYPE_STRING;
}

/**
 * set sheet data
 * @param object $active_sheet PHPExcel Instance
 * @param array $row_data
 * @param array $colconfig
 */
function setSheetData($active_sheet,$row_data,$colconfig)
{
	$rcnt = count($row_data);
	for ($i=0; $i<$rcnt; $i++)
	{
		$cellIdx = 0;
		$rowIdx = $i+2;
		foreach ($row_data[$i] as $k=>$val)
		{
			$data_type = getColDataType($colconfig,$k);
			$active_sheet->setCellValueByColumnAndRow($cellIdx,$rowIdx,$val);
			if ($data_type != 'date')
			$active_sheet->getCellByColumnAndRow($cellIdx,$rowIdx)->setValueExplicit($val,$data_type);
			$cellIdx++;
		}
	}
}

/**
 * Set Column width auto size
 * 
 * @param Object $active_sheet
 * @param array $colconfig
 */
function setColAutoSize($active_sheet,$colconfig)
{
	$col_cnt = count($colconfig);
	for ($i = 0; $i <= $col_cnt; $i++) 
	{
		$active_sheet->getColumnDimension(chr(65+$i))->setAutoSize(true);
	}
}

$col_config = getGVColumnConfig($appid,$lang);
setColAutoSize($currSheet, $col_config);
setSheetRowTitle($currSheet,$col_config);
$recordset = getData($_POST['lastsql']);
setSheetData($currSheet,$recordset,$col_config);

$filename = iconv('utf-8','gbk',$reportname).'_'.date('Ymdhis').'.xls';
// output to file
// output to browser to download
// for remove utf8 bom
ob_end_clean(); // Added by me
ob_start(); // Added by me
//header("Content-Type:application/vnd.ms-excel; charset=utf8");
header("Content-Type: application/force-download");
header("Content-Type: application/octet-stream");
header("Content-Type: application/download");
//header('Content-Disposition:inline;filename="'.$outputFileName.'"');
header("Content-Disposition: attachment; filename=".$filename);
header("Content-Transfer-Encoding: binary");
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
header("Cache-Control: must-ridate, post-check=0, pre-check=0");
header("Cache-Control: max-age=0");
header("Pragma: no-cache");
$writer = PHPExcel_IOFactory::createWriter($phpExcel,'Excel5');
$writer->save('php://output'); 
exit;
